global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
#  - job_name: prometheussss
#    static_configs:
#      - targets: [localhost:9090]
  - job_name: 'spring-actuator'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8800}']